- name: Deploy Flask App Locally
  hosts: localhost
  become: yes
  tasks:
    - name: Install Python & pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Ensure app directory exists
      file:
        path: /home/ubuntu
        state: directory

    - name: Copy app.py to target
      copy:
        src: app.py
        dest: /home/ubuntu/app.py
        mode: '0755'

    - name: Copy templates folder to target
      copy:
        src: templates/
        dest: /home/ubuntu/templates/
        mode: '0755'

    - name: Install Flask
      pip:
        name: Flask==2.3.2
        executable: pip3

    - name: Run Flask app
      shell: nohup python3 /home/ubuntu/app.py &
