- name: Deploy Flask App Locally
  hosts: localhost
  become: yes
  tasks:
    - name: Install Python & pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask
      pip:
        name: Flask==2.3.2
        executable: pip3

    - name: Copy app
      copy:
        src: app.py
        dest: /home/ubuntu/app.py
        mode: '0755'

    - name: Run Flask app
      shell: nohup python3 /home/ubuntu/app.py &
